name: Publish to npm Registry

on:
#  workflow_run:
#    workflows: ["Build"]
#    branches: [master]
#    types:
#      - completed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }} && !contains(github.event.head_commit.message, '[no-publish]')
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
      - name: Setup git repo
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - name: Version and publish to npm
        run: |
          npm version minor --force -m "Version %s [skip ci]"
          npm set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: npm_logs
          path: /home/runner/.npm/_logs/
      - name: Push release commit and tag to GitHub
        run: git push gh-origin HEAD:master --tags
